---
title: "git_01"
author: "Amir Johnson"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A BOAT beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July --  
Children three that nestle near,  
Eager eye and willing ear, 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
I was drowning amidst a storm of self-doubt and hatred  
The sewage of my own thoughts flooding over my head,  
Choking me,  
Filling my lungs with vile filth until I could no longer breathe.  
I cried out with my final breath, a mournful, ghostly sound,  
The sound of a soul that was stuck between life and death.  
And the stars shivered amidst the darkness,  
For the death of a soul makes the whole universe weep  
The missing piece can never be replaced.  
And there, above it all, you stood -  
My knight, my hope, my saviour  
My love.  